### ISSUE TITLE
[SELF-REPORT] Manuel González

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#160]
# Self Report
## Tasks

- [ ] Creating Database Schema [issue 100](https://github.com/Arquisoft/wiq_es1c/issues/100)
  - Pending draft architecture decision for database [issue 34](https://github.com/Arquisoft/wiq_es1c/issues/34)
- [x] Creating Templates of Questions [issue 4](https://github.com/Arquisoft/wiq_es1c/issues/4)
  - Added questions with images
  - Added questions with category `history` and `geography`
- [x] Creating a miro board which represents the actual data model [miro board](https://miro.com/app/board/uXjVN9ntiDg=/?share_link_id=190660897067)
