### ISSUE TITLE
[SELF-REPORT] MANUEL

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#236]
# Self Report - 3
## Tasks
- Make Acceptance Tests [issue 179](https://github.com/Arquisoft/wiq_es1c/issues/179) 
  - Pending to Update Tests for Merge [Pull Request #227](https://github.com/Arquisoft/wiq_es1c/pull/227)
    - I have to remove ***mariadb*** package and database queries because they are not able to use on GitHub  
 - Deploy application in azure
## Troubles
- I have had difficulties using docker engine on Windows, because my machine has 8 GB of main memory and `docker compose --profile dev up --build` took me 45 minutes. This problem was slowing me down a lot and I had to upgrade computer memory to speed up development.

**Comment by gs-Manuel** [comment]
# Self Report - 2
## Tasks

- [ ] Creating Database Schema [issue 100](https://github.com/Arquisoft/wiq_es1c/issues/100)
  - Pending draft architecture decision for database [issue 34](https://github.com/Arquisoft/wiq_es1c/issues/34)
- [x] Creating Templates of Questions [issue 4](https://github.com/Arquisoft/wiq_es1c/issues/4)
  - Added questions with images
  - Added questions with category `history` and `geography`
- [x] Creating a miro board which represents the actual data model [miro board](https://miro.com/app/board/uXjVN9ntiDg=/?share_link_id=190660897067)

**Comment by gs-Manuel** [comment]
# Self Report - 1
## Tasks
1. Learned about tech stack we are using for this architecture solution [DRAFT](https://github.com/Arquisoft/wiq_es1c/issues/34) thanks to @Manueluz [Tutorials](https://github.com/Arquisoft/wiq_es1c/issues/5)
2. Made the documentation for [Section-1](https://github.com/Arquisoft/wiq_es1c/issues/59) and [Section-2](https://github.com/Arquisoft/wiq_es1c/issues/60) following Arch42 template as team agreed: [6/02 - Meeting](https://github.com/Arquisoft/wiq_es1c/wiki/06-02-2024)
3. Suggested using SCRUM as work methodology [Agile - SCRUM](https://github.com/Arquisoft/wiq_es1c/blob/master/docs/src/04_solution_strategy.adoc#work-methodology-decissions)
4. Reviewed sections 3, 4, 5, 6 of documentation: [Review Documentation](https://github.com/Arquisoft/wiq_es1c/issues/79)

**Comment by gs-Manuel** [comment]
# Self Report - 4
## Tasks
- Make Acceptance Tests [issue 179](https://github.com/Arquisoft/wiq_es1c/issues/179) 
  - Merged in [Pull Request #280](https://github.com/Arquisoft/wiq_es1c/pull/280) 
 - Deploy application in azure and manage troubles 
- Worked in documentation [Issue 261](https://github.com/Arquisoft/wiq_es1c/issues/261) 
  - Merged in [Pull Request #287](https://github.com/Arquisoft/wiq_es1c/pull/287)
## Troubles
- We encountered issues with database migrations for acceptance tests, for which the following branch [Pull Request #280](https://github.com/Arquisoft/wiq_es1c/pull/280) was created by @Manueluz , closing the old e2e test development branch [Pull Request #219](https://github.com/Arquisoft/wiq_es1c/pull/219). 
He also resolved this issue, and I was able to continue developing the tests.
